; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy
name = car26
description = Wazzu Racing 2026 Car 92 Embedded Code

[env:teensy]
platform = teensy
board = teensy41
framework = arduino
build_src_filter = +<teensy/*>
lib_deps = 
	adafruit/Adafruit BusIO@^1.17.4
	https://github.com/mantonakakis1/MegaCAN
	sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.28
lib_compat_mode = soft

[env:radio_car]
platform = atmelavr
board = feather32u4
framework = arduino
build_src_filter = +<radio_car/*>
lib_deps = 
	mikem/RadioHead@^1.120
	sparkfun/SparkFun u-blox Arduino Library@^1.8.11

[env:radio_telemetry]
platform = atmelavr
board = feather32u4
framework = arduino
build_src_filter = +<radio_telemetry/*>
lib_deps = 
	mikem/RadioHead@^1.120
	sparkfun/SparkFun u-blox Arduino Library@^1.8.11
